In [ ]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
T = tuple(range(10))
T

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

# Motivación

¿Recuerdan algo de álgebra lineal? Por ejemplo:
- vectores;
- suma de vectores;
- producto por un escalar ...

¿Cómo se les ocurre que podríamos manejar lo anterior en Python?

In [ ]:
# Crear dos vectores
x = [4, 5, 8, -2, 3]
y = [3, 1, -7, -9, 5]

In [ ]:
# Suma de vectores  [4+3 , 5+1, 8-7, ...]
x + y

[4, 5, 8, -2, 3, 3, 1, -7, -9, 5]

In [ ]:
# ¿con ciclos quizá?
sum_ = [x[i] + y[i] for i in range(len(x))]
sum_

[7, 6, 1, -11, 8]

In [ ]:
# Producto escaler 
3*x 

[4, 5, 8, -2, 3, 4, 5, 8, -2, 3, 4, 5, 8, -2, 3]

In [ ]:
# ¿con ciclos quizá?
prod_ = [3 * x[i] for i in range(len(x))]
prod_

[12, 15, 24, -6, 9]

### Solución: NumPy

NumPy es la librería fundamental para computación científica con Python. Contiene, entre otros:
- una clase de objetos tipo arreglo N-dimensional muy poderso;
- funciones matemáticas sofisticadas;
- herramientas matemáticas útiles de álgebra lineal, transformada de Fourier y números aleatorios.

Aparte de sus usos científicos, NumPy puede ser usada como un contenedor eficiente de datos multidimensional, lo que le otorga a NumPy una capacidad impresionante de integración con bases de datos.

Por otra parte, casi todas las librerías de Python relacionadas con ciencia de datos y machine learning tales como SciPy (Scientific Python), Mat-plotlib (librería de gráficos), Scikit-learn, dependen de NumPy razonablemente.

In [ ]:
#pip! install numpy
#conda install numpy 
import numpy as np

In [ ]:
# sin(pi/2)
np.sin(np.pi/2)

1.0

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [ ]:
np.array( [1, 2, 3]   )

array([1, 2, 3])

In [ ]:
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Np_cero = np.zeros(10)
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
Np_uno = np.ones(10, dtype = int)
Np_uno

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
Np_relleno = np.full(10, 256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [ ]:
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Np_random_dimensiones = np.random.randint( 10, size=(3,4))
Np_random_dimensiones

array([[4, 4, 6, 0],
       [0, 3, 0, 5],
       [0, 3, 5, 1]])

In [ ]:
Np_cero.ndim

1

In [ ]:
Np_random_dimensiones.ndim

2

In [ ]:
Np_random_dimensiones.shape

(5, 16)

In [ ]:
Np_random_dimensiones.size

12

In [ ]:
Np_uno.dtype

dtype('int64')

In [ ]:
Np_random_dimensiones.itemsize

8

In [ ]:
Np_cero.nbytes

80

In [ ]:
rango = range(1,11)
Np_diez_numeros = np.array(rango)
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
Np_diez_numeros[0]

1

In [ ]:
Np_diez_numeros[3]

4

In [ ]:
Np_diez_numeros[-3]

8

In [ ]:
Np_random_dimensiones

array([[4, 4, 6, 0],
       [0, 3, 0, 5],
       [0, 3, 5, 1]])

In [ ]:
Np_random_dimensiones[1,3]

5

In [ ]:
Np_diez_numeros[:3]

array([1, 2, 3])

In [ ]:
Np_diez_numeros[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
Np_diez_numeros[4:7]

array([5, 6, 7])

In [ ]:
Np_diez_numeros[: :2]

array([1, 3, 5, 7, 9])

In [ ]:
Np_diez_numeros[2:6]

array([3, 4, 5, 6])

In [ ]:
Np_random_dimensiones

array([[4, 4, 6, 0],
       [0, 3, 0, 5],
       [0, 3, 5, 1]])

In [ ]:
Np_random_dimensiones[0:2, 0:2]

array([[4, 4],
       [0, 3]])

In [ ]:
np.arange(1,65)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [ ]:
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

## Concatenar

### Consiste en formar un nuevo arreglo a partir de “enganchar” o “apilar” otros.
Python ofrece dos métodos:
- Con la operación concatenate. 
- Con las operaciones vstack y hstack 


In [ ]:
Array_1 = np.random.randint(10, size = 5)
Array_1

array([9, 1, 9, 4, 7])

In [ ]:
Array_2 = np.random.randint(10, size = 5)
Array_2

array([0, 3, 4, 8, 7])

In [ ]:
Arrays_concatenados = np.concatenate([Array_1, Array_2])
Arrays_concatenados

array([9, 1, 9, 4, 7, 0, 3, 4, 8, 7])

In [ ]:
Array_extra = np.array( [[10], [20]] )
Array_extra

array([[10],
       [20]])

### El método vstack apila verticalmente:


In [ ]:
Array_apilados_v = np.vstack([Array_extra, Array_extra])
Array_apilados_v

array([[10],
       [20],
       [10],
       [20]])

###El método hstack apila horizontalmente:

In [ ]:
Array_apilados_h = np.hstack([Array_extra, Array_extra])
Array_apilados_h

array([[10, 10],
       [20, 20]])

## Transponse

In [ ]:
A = np.array( [ [1,4,7], [2,5,8], [3,6,9] ,[10,11,12]   ]  )
A

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [10, 11, 12]])

In [ ]:
X = np.transpose(A)
X

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [ ]:
Arrays_concatenados

array([9, 1, 9, 4, 7, 0, 3, 4, 8, 7])

In [ ]:
Array_partido1 , Array_partido2, Array_partido3= np.split(Arrays_concatenados, [2,6])
Array_partido1

array([9, 1])

In [ ]:
Array_partido2

array([9, 4, 7, 0])

In [ ]:
Array_partido3

array([3, 4, 8, 7])

In [ ]:
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [ ]:
Ajedrez_partido_1 , Ajedrez_partido2 = np.hsplit(Ajedrez_64, [4])
Ajedrez_partido2

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [21, 22, 23, 24],
       [29, 30, 31, 32],
       [37, 38, 39, 40],
       [45, 46, 47, 48],
       [53, 54, 55, 56],
       [61, 62, 63, 64]])

In [ ]:
Ajedrez_partido_1 , Ajedrez_partido2 = np.vsplit(Ajedrez_64, [4])
Ajedrez_partido2

array([[33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [ ]:
Array_1.mean()

6.0

In [ ]:
Array_1 + Array_2

array([ 9,  4, 13, 12, 14])

In [ ]:
np.std(Array_1)

3.0983866769659336

In [ ]:
import pandas as pd
import numpy as np
import ast

def getArrayFromDrive():
    """La siguiente funcion obtiene el archivo en google Spreadsheet, lo transforma en un dataframe 
    y obtiene la columna a trabajar que es la columna de Salario mensual NETO y devuelve un numpy array luego 
    de haber borrado los valores nulos de la columna.
    
    """
    sheet_url = "https://docs.google.com/spreadsheets/d/15Stnum8mI9QdwF9ZiPFCe3_qG9XyZyNzmOSIDunzPjA/view#gid=255849258"
    url = sheet_url.replace("/view#gid=", "/export?format=csv&gid=")
    df = pd.read_csv(url)
    
    return df["Salario mensual NETO (en tu moneda local)"].dropna().to_numpy()

In [ ]:
salario_neto = getArrayFromDrive()
salario_neto

array(['43000', '63000', '127000', ..., '45.753', '72', '65000'],
      dtype=object)