Measuring Times

In [3]:
import numpy as np
import timeit

listado=list(range(1001))

array=np.arange(1001)

def suma(listado):
    suma = 0
    for i in listado:
        suma += i
    return suma

%timeit suma(listado)

%timeit array.sum()

36.4 µs ± 1.51 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
1.98 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Ejercicio N 1

In [4]:

randomArray = np.random.randint(0, 100, 100)
randomArray

array([86, 51, 13, 31,  0, 81, 39, 50, 30, 79,  1, 12, 24, 32, 15, 32,  8,
       29, 53, 49, 79, 57, 27, 50,  5, 58, 88, 97, 44, 11, 91, 67, 71, 14,
       77, 96, 54, 84, 18, 55, 26, 96,  1, 77, 78, 24, 11, 87, 32, 79, 26,
       99, 56, 32, 49, 65, 53, 89, 71, 30,  1, 43, 51, 12, 25,  2, 43, 65,
       57, 99, 72, 81, 72, 29, 76, 97, 23, 53, 81, 64, 70, 82, 97, 91, 66,
       45, 79, 67,  6, 62, 68, 95, 26,  5, 84, 86, 41, 59, 49, 97])

In [5]:
randomArray_median = np.median(randomArray)
randomArray_median

53.5

Ejercicio N 2

In [6]:
import scipy.special # For calculating factorial, can accept np.ndarray

scipy.special.factorial(randomArray)

array([2.42270954e+130, 1.55111875e+066, 6.22702080e+009, 8.22283865e+033,
       1.00000000e+000, 5.79712602e+120, 2.03978821e+046, 3.04140932e+064,
       2.65252860e+032, 8.94618213e+116, 1.00000000e+000, 4.79001600e+008,
       6.20448402e+023, 2.63130837e+035, 1.30767437e+012, 2.63130837e+035,
       4.03200000e+004, 8.84176199e+030, 4.27488328e+069, 6.08281864e+062,
       8.94618213e+116, 4.05269195e+076, 1.08888695e+028, 3.04140932e+064,
       1.20000000e+002, 2.35056133e+078, 1.85482642e+134, 9.61927597e+151,
       2.65827157e+054, 3.99168000e+007, 1.35200153e+140, 3.64711109e+094,
       8.50478589e+101, 8.71782912e+010, 1.45183092e+113, 9.91677935e+149,
       2.30843697e+071, 3.31424013e+126, 6.40237371e+015, 1.26964034e+073,
       4.03291461e+026, 9.91677935e+149, 1.00000000e+000, 1.45183092e+113,
       1.13242812e+115, 6.20448402e+023, 3.99168000e+007, 2.10775730e+132,
       2.63130837e+035, 8.94618213e+116, 4.03291461e+026, 9.33262154e+155,
       7.10998588e+074, 2

In [7]:
x = 8
y = 23

a = np.arange(x, y)
a[np.logical_and(a>=x,a<y+1)]
a.sum()

225

Ejercicio N 2 FIXED - Agrego funciones de la primer entrega

In [8]:
def factorial(x):	# función “factorial”. 
    return 	scipy.special.factorial(x)

res = factorial(4)
print (res)

24.0


In [18]:
def custom_function(x,y):
    if y > x:
        a = np.arange(x, y+1)
        a[np.logical_and(a>=x,a<y+1)]
        return a.sum()
    else:
        return "y debe ser mayor a x"

res = custom_function(2,4)
print('x>y --> res= %d' % res)
res2 = custom_function(4,2)
print(res2)

[2 3 4]
[2 3 4]
x>y --> res= 9
y debe ser mayor a x


Ejercicio N 3

In [9]:
import pandas as pd
import numpy as np
import ast

def getArrayFromDrive():
    """La siguiente funcion obtiene el archivo en google Spreadsheet, lo transforma en un dataframe 
    y obtiene la columna a trabajar que es la columna de Salario mensual NETO y devuelve un numpy array luego 
    de haber borrado los valores nulos de la columna.
    
    """
    sheet_url = "https://docs.google.com/spreadsheets/d/15Stnum8mI9QdwF9ZiPFCe3_qG9XyZyNzmOSIDunzPjA/view#gid=255849258"
    url = sheet_url.replace("/view#gid=", "/export?format=csv&gid=")
    df = pd.read_csv(url)
    
    return pd.to_numeric(df["Salario mensual NETO (en tu moneda local)"],errors='coerce').dropna().to_numpy()

salario_neto = getArrayFromDrive()
salario_neto

array([4.3000e+04, 6.3000e+04, 1.2700e+05, ..., 4.5753e+01, 7.2000e+01,
       6.5000e+04])

In [10]:
#median value
median = np.median(salario_neto)
median

76000.0

In [11]:
#mean value
mean = np.mean(salario_neto)
mean

19306004.37798064