In [ ]:
import numpy as np

### Problema 1

> Dados cinco (5) contenedores cilíndricos con diferentes radios y alturas que pueden variar entre 5 y 25 cm, encontrar:
> 1. El volumen del agua que puede almacenar cada contenedor;
> 2. El volumen total del agua que pueden almacenar todos los contenedores juntos;
> 3. Cual contenedor puede almacenar más volumen, y cuanto;
> 4. Cual contenedor puede almacenar menos volumen, y cuanto;
> 5. Obtener la media, la mediana y la desviación estándar de los volúmenes de agua que pueden ser almacenados en los contenedores.

In [ ]:
# Definir número de contenedores, medida mínima y máxima
n_contenedores = 5
medida_min = 5
medida_max = 25

A continuación, generararemos un arreglo de números aleatorios entre 5 y 25 mn que representarán los radios y alturas de los cilindros

In [ ]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [ ]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of numpy.random.mtrand.RandomState instance
    seed(self, seed=None)
    
    Reseed a legacy MT19937 BitGenerator
    
    Notes
    -----
    This is a convenience, legacy function.
    
    The best practice is to **not** reseed a BitGenerator, rather to
    recreate a new one. This method is here for legacy reasons.
    This example demonstrates best practice.
    
    >>> from numpy.random import MT19937
    >>> from numpy.random import RandomState, SeedSequence
    >>> rs = RandomState(MT19937(SeedSequence(123456789)))
    # Later, you want to restart the stream
    >>> rs = RandomState(MT19937(SeedSequence(987654321)))



In [ ]:
# Números aleatorios que representan radios y alturas.
# Inicializar la semilla
np.random.seed(1001)
medidas = np.random.randint(medida_min, medida_max, size=((10,)))

In [ ]:
medidas

array([18, 14, 19,  8, 17, 13, 19,  8,  9, 18])

In [ ]:
medidas = medidas.reshape((2,5))
medidas

array([[18, 14, 19,  8, 17],
       [13, 19,  8,  9, 18]])

In [ ]:
# Radios - primer renglón de medidas
radios = medidas[0, :]
radios

array([18, 14, 19,  8, 17])

In [ ]:
alturas = medidas[1, :]
alturas

array([13, 19,  8,  9, 18])

Ya podemos calcular los volúmenes

In [ ]:
volumenes = (np.pi * radios ** 2) * alturas
volumenes

array([13232.38825692, 11699.29104197,  9072.91958357,  1809.55736847,
       16342.56498397])

In [ ]:
# Volumen total
volumenes.sum()

52156.72123489774

In [ ]:
# Contenedor que puede almacenar más volumen
volumenes.argmax( )

4

In [ ]:
# volumen máximo
volumenes.max()

16342.564983974104

In [ ]:
max(volumenes)

16342.564983974104

In [ ]:
# revisar la optimización de numpy
random_vector = np.random.randint(0, 1000, size=(1000,))

In [ ]:
%timeit random_vector.max()

The slowest run took 83.24 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.6 µs per loop


In [ ]:
%timeit np.max(random_vector)

The slowest run took 13.71 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 5.11 µs per loop


In [ ]:
%timeit max(random_vector)

10000 loops, best of 5: 65.7 µs per loop


In [ ]:
# Contenedor que puede almacenar menos volumen
volumenes.argmin( )

3

In [ ]:
volumenes.min()

1809.5573684677208

In [ ]:
# Media, mediana y desviación estándar
volumenes.mean(), volumenes.std()

(10431.344246979548, 4910.735052243538)

In [ ]:
np.median(volumenes)

11699.291041968389

### Problema 2

> 25 cartas numeradas de la 1 a la 25 se distribuyen aleatoriamente y en partes iguales a 5 personas. Encuentre la suma de cartas para cada persona tal que: 
> - para la primera persona, la suma es el valor de la primera carta menos la suma del resto de las cartas;
> - para la segunda persona, la suma es el valor de la segunda carta menos la suma del resto de las cartas;
> - y así sucesivamente ...

> La persona para la cual la suma sea mayor, será el ganador. Encontrar el ganador.

In [ ]:
cartas = np.arange(1,26)
cartas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of numpy.random.mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    .. note::
        New code should use the ``shuffle`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.
    
    Returns
    -------
    None
    
    See Also
    --------
    Generator.shuffle: which should be used for new code.
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> ar

In [ ]:
np.random.shuffle(cartas)
cartas

array([13, 16, 17, 12,  9, 11, 23, 14,  3,  7, 19, 25, 20, 24,  1,  8, 18,
        6, 22, 21, 15,  4,  5, 10,  2])

In [43]:
cartas = cartas.reshape((5,5))
cartas

array([[13, 16, 17, 12,  9],
       [11, 23, 14,  3,  7],
       [19, 25, 20, 24,  1],
       [ 8, 18,  6, 22, 21],
       [15,  4,  5, 10,  2]])

In [44]:
I5 = np.eye(5)
I5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
I5 * cartas

array([[13.,  0.,  0.,  0.,  0.],
       [ 0., 23.,  0.,  0.,  0.],
       [ 0.,  0., 20.,  0.,  0.],
       [ 0.,  0.,  0., 22.,  0.],
       [ 0.,  0.,  0.,  0.,  2.]])

In [56]:
complement = np.ones((5,5)) - I5
complement

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [49]:
complement * cartas

array([[ 0., 16., 17., 12.,  9.],
       [11.,  0., 14.,  3.,  7.],
       [19., 25.,  0., 24.,  1.],
       [ 8., 18.,  6.,  0., 21.],
       [15.,  4.,  5., 10.,  0.]])

In [50]:
matriz_para_suma = I5 * cartas - complement * cartas
matriz_para_suma

array([[ 13., -16., -17., -12.,  -9.],
       [-11.,  23., -14.,  -3.,  -7.],
       [-19., -25.,  20., -24.,  -1.],
       [ -8., -18.,  -6.,  22., -21.],
       [-15.,  -4.,  -5., -10.,   2.]])

In [60]:
suma = matriz_para_suma.sum(axis = 0)
suma

array([-40., -40., -22., -27., -36.])

¿Quién es el ganador?

In [55]:
suma.argmax()

2